### ISSUE TITLE
How to implement this solution in a Angular 2 project?

### ISSUE THREAD

**Issue by raufemm** [DevExpress-Examples/dxdatagrid-how-to-implement-a-three-state-select-all-check-box-for-in-a-group-row-t444368#1]
How to implement this solution in a Angular 2 project?

I try to use this solution, but a I'm not any results.

**Comment by artem-kurchenko** [comment]
Hi,

We don't have a similar example for Angular in our database yet. The main differences are: 
1. You need to define a [groupCellTemplate](https://js.devexpress.com/Documentation/18_1/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#groupCellTemplate) using [dxTemplate](https://js.devexpress.com/Documentation/18_1/ApiReference/UI_Widgets/Markup_Components/dxTemplate/) as described at [Custom Templates](https://github.com/DevExpress/devextreme-angular#custom-templates)
2. Our Angular integration doesn't use jQuery by default (see [jQuery Integration](https://github.com/DevExpress/devextreme-angular#include-jquery-integration)) So, you need to replace all jQuery API with native JavaScript methods.

For more detailed assistance, please submit a [ticket](https://www.devexpress.com/Support/Center/Question/Create) in our Support Center and describe what part doesn't work in greater detail. We'll be happy to help.
